language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly


before_script:
    - composer install

script:
    - ./vendor/bin/phpunit
